### ISSUE TITLE
mysql DB upgrade error (MariaDB 10.1)

### ISSUE THREAD

**Issue by thuso607** [filesender/filesender#829] opened 2020-08-04 21:57 UTC
I am trying to run the database script on version 2.18 and I come across this error: 

# [upgrade:error] [DBIUsageException details uid:5f29d6fc73cb9] "SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'varchar(255))  and target_type = 'Transfer'  UNION select t.*,0 as fileid,a.crea' at line 1"

kindly help me to resolve this issue

**Comment by monkeyiq** [comment] 2020-08-06 03:42
Which version of MariaDB are you using (might help me to reproduce it locally). Is there any more detail from the logs. Sometimes there is something in there about which query is causing the issue.

**Comment by thuso607** [comment] 2020-08-06 05:22
I am using MariaDB 10.1. The attached screenshot includes further details from the logs.

![MariaDB error](https://user-images.githubusercontent.com/22442842/89493901-61516c80-d7b5-11ea-9a80-77cfa46044d7.PNG)

**Comment by thuso607** [comment] 2020-08-06 05:39
The query causing this issue is the following:

CREATE OR REPLACE VIEW transfersauditlogsview as select t.*,0 as fileid,a.created as acreated,a.author_type,a.author_id,a.target_type,a.target_id,a.event,a.id as aid from Transfers t, AuditLogs a where a.target_id=cast(t.id as varchar(255)) and target_type = 'Transfer' UNION select t.*,0 as fileid,a.created as acreated,a.author_type,a.author_id,a.target_type,a.target_id,a.event,a.id as aid from Transfers t, AuditLogs a, Files f where f.transfer_id=t.id and a.target_id=cast(f.id as varchar(255)) and target_type = 'File'

**Comment by bepstein** [comment] 2020-09-01 13:54
I ran into this issue.  I replaced 'varchar(255)' to 'char(255)' in classes/data/Transfer.class.php and this issue went away.

I'm using MariaDB-server-10.1.46-1.el7.centos.x86_64.

Afterward, though, I ran into a new issue.

This is with a new 2.19 installation on CentOS 7.8

**Comment by bepstein** [comment] 2020-09-01 14:27
Upgrading to MariaDB 10.5 solved this issue for me, and the new one that was introduced as well.

**Comment by monkeyiq** [comment] 2020-09-05 07:32
Is there any chance to update to a slightly newer MariaDB. I think there were a number of issues with the 10.0 and 10.1 versions which might mean that if this specific issue is worked around then it may lead us to another issue. IIRC 10.2 was used by some folks with active installations. I am on 10.4.13-MariaDB which FWIW resolves the above view definition (repeated below).

```
MariaDB [filesender]> CREATE OR REPLACE VIEW transfersauditlogsviewtest as 
  select t.*,0 as fileid,a.created as acreated,a.author_type,a.author_id,a.target_type,a.target_id,a.event,a.id as aid 
  from Transfers t, AuditLogs a where a.target_id=cast(t.id as varchar(255)) and target_type = 'Transfer' 
UNION 
  select t.*,0 as fileid,a.created as acreated,a.author_type,a.author_id,a.target_type,a.target_id,a.event,a.id as aid 
  from Transfers t, AuditLogs a, Files f where f.transfer_id=t.id and a.target_id=cast(f.id as char(255)) 
  and target_type = 'File';
Query OK, 0 rows affected (0.196 sec)
```
I will setup a 10.0 MariaDB to take a look at what might be changed to make this view definition work.

**Comment by monkeyiq** [comment] 2020-09-05 07:54
So it seems that view wants at least mariadb 10.3 to execute as written. Now to work out how to relieve that requirement.

**Comment by monkeyiq** [comment] 2020-09-06 05:14
I have an update in https://github.com/filesender/filesender/pull/833 which I will merge once CI is happy with things. I have tested that against 10.1 and 10.0 locally including a file upload/download round trip. Selenium seems to be timing out at the moment.

**Comment by monkeyiq** [comment] 2020-09-20 01:41
It seems CI is not happy with the Selenium link at the moment. I have merged 833 into development which makes things work on earlier MariaDB versions.

**Comment by monkeyiq** [comment] 2020-12-18 00:54
A fix for this has been merged. This should be in 2.20 and later.

**Closed by monkeyiq** 2020-12-18 00:54 UTC
Labels: fix merged
