### ISSUE TITLE
can't set a expire date in the future: bad_expire

### ISSUE THREAD

**Issue by xvazquezc** [filesender/filesender#245] opened 2018-02-07 00:57 UTC
Hi there,
I've been trying to use the REST API with CloudStor as recipient of the files but there is a problem setting expire dates:
If I set a date in the future (e.g. expire in 1 month), the files don't get through and get this kind of error:
```
EXCEPTION [0] Http error 500 : {"message":"bad_expire","uid":"5a793618787e5","details":null}
```
If date is current or sometime in the past: data is uploaded and get notification email... but because the expire date is passed the download link is obviously expired. The files are uploaded to the server, if I access to CloudStor via web I can see them but the notification emails are pretty much useless (expired links)
I used a php file based on the sample from CloudStor
https://support.aarnet.edu.au/hc/en-us/articles/235972948-Does-CloudStor-FileSender-provide-access-to-an-API-
https://support.aarnet.edu.au/hc/en-us/article_attachments/333757064535/FilesenderRestClient.php

Has anybody experience anything like this?
Not sure if it's a FileSender or CloudStor issue. I also contacted them just in case.
Thank you,
Xabi

**Comment by WebSpider** [comment] 2021-03-10 08:56
@xvazquezc Did you ever solve this issue with CloudStor?

**Comment by xvazquezc** [comment] 2021-03-11 00:53
@WebSpider no, sorry. This is something that I stopped chasing - in part because our server still uses FileSender 1.6 and the API was introduced in v2.

**Comment by WebSpider** [comment] 2021-03-11 08:10
AFAIK filesender 1.6 is largely unmaintained, and not audited recently, so I would indeed recommend upgrading to filesender v2. As filesender does not seem to be the root cause, I'd suggest closing the issue for now.

**Closed** 2021-03-11 22:32 UTC
