### ISSUE TITLE
Sanity Check fails during file upload

### ISSUE THREAD

**Issue by thuso607** [filesender/filesender#1913] opened 2024-05-28 13:36 UTC
What causes the following sanity_check_ error. See the output below:

[2024-05-24 14:20:36] [rest:info] authentication::create(2) FOUND AND RETURNING 763
[2024-05-24 14:25:39] [user 767] [rest:error] [RestSanityCheckFailedException exception uid:66509553966d2] rest_sanity_check_failed
[2024-05-24 14:25:39] [user 767] [rest:error] [RestSanityCheckFailedException trace uid:66509553966d2] #0 /opt/filesender/filesender-2.45/classes/rest/RestServer.class.php(299): RestEndpointFile->put()
[2024-05-24 14:25:39] [user 767] [rest:error] [RestSanityCheckFailedException trace uid:66509553966d2] #1 /opt/filesender/filesender-2.45/www/rest.php(37): RestServer::process()
[2024-05-24 14:25:39] [user 767] [rest:error] [RestSanityCheckFailedException trace uid:66509553966d2] #2 {main}
[2024-05-24 14:25:39] [user 767] [rest:error] [RestSanityCheckFailedException details uid:66509553966d2] method = "put"
[2024-05-24 14:25:39] [user 767] [rest:error] [RestSanityCheckFailedException details uid:66509553966d2] endpoint = "file"
[2024-05-24 14:25:39] [user 767] [rest:error] [RestSanityCheckFailedException details uid:66509553966d2] "check "chunk_size", "357939" value was expected but got "262144" instead"

The terasender_worker_count is set to 5.

**Comment by monkeyiq** [comment] 2024-06-03 23:09
I am not sure what exactly causes this. Given that the expected value is different to a nice nominal chunk size this appears to be happening on the last chunk of the upload (which is the only one that could be smaller than the nominal chunk size).

Do you know if this was for an encrypted file? Which version of FileSender? Is this reproducible locally?

If a chunk upload breaks off without fully completing you can get these which might happen for example when trying to force things by navigating to another site mid upload. The server just sees that the connection for that chunk has closed and not transferred the full expected amount.

**Comment by WebSpider** [comment] 2024-06-07 07:59
I have access to several installs that have this error as well, and can probably help reproduce it. So far, we have been able to ignore the error without issues (that we know of).

**Comment by WebSpider** [comment] 2024-06-07 08:12
Duplicate of #76

**Comment by monkeyiq** [comment] 2024-06-11 04:39
I am not sure much can be done about this one. FileSender should reattempt the chunk and continue the upload.

Let me know if you are getting excessive amounts of this error.

**Closed** 2024-06-14 23:49 UTC
