### ISSUE TITLE
Kanji characters in message cause 'Failed to access database' error

### ISSUE THREAD

**Issue by hughmll** [filesender/filesender#1231] opened 2022-04-06 06:06 UTC
Hi all,

Having an issue where FileSender throws a 'Failed to access database' error when attempting to send a file with Kanji characters in the message body. As soon as Kanji characters are removed, the upload is successful.

Please see attached images for pre-send settings and post-send error. I've been able to replicate this consistently.

![Pre-send](https://user-images.githubusercontent.com/45057758/161906271-fadd1437-b266-473b-9df8-f1fb5ce62625.png)
![Post-send](https://user-images.githubusercontent.com/45057758/161906278-858b5a3a-d831-413c-9dcd-6ba9ca48b856.PNG)

**Comment by monkeyiq** [comment] 2022-04-07 06:22
Do you know which version of FileSender this is and what database + version is backing it? From the looks of the interface this might be aarnet (which I have tested and reproduced the issue on).

I am not sure if my input methods are generating the right / same text. I have tried with postgresql and mariadb backing and can upload on my local install ok using the below message text. Though aarnet doesn't upload ok :(

```
m3 日本
```

**Comment by madsi1m** [comment] 2022-04-08 04:52
Hi, we are on master-filesender-2.24 + mariadb 10.3

looking at the show create table Transfers it seems we are set to latin1 somehow? Is this something historic or from a upgrade migration?

```
CREATE TABLE `Transfers` (
  `id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `user_email` varchar(250) CHARACTER SET latin1 NOT NULL,
  `guest_id` mediumint(8) unsigned DEFAULT NULL,
  `lang` varchar(8) CHARACTER SET latin1 DEFAULT NULL,
  `subject` varchar(250) CHARACTER SET latin1 DEFAULT NULL,
  `message` text CHARACTER SET latin1 DEFAULT NULL,
  `created` datetime NOT NULL,
  `made_available` datetime DEFAULT NULL,
  `expires` datetime NOT NULL,
  `expiry_extensions` smallint(5) unsigned NOT NULL DEFAULT 0,
  `status` varchar(32) CHARACTER SET latin1 NOT NULL,
  `options` text CHARACTER SET latin1 NOT NULL,
  `userid` bigint(20) unsigned NOT NULL,
  `key_version` smallint(5) unsigned NOT NULL DEFAULT 0,
  `salt` varchar(32) DEFAULT NULL,
  `password_version` smallint(5) unsigned NOT NULL DEFAULT 1,
  `password_encoding` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `password_hash_iterations` bigint(20) unsigned NOT NULL DEFAULT 150000,
  `client_entropy` varchar(44) DEFAULT NULL,
  `roundtriptoken` varchar(44) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `Transfers_userid` (`userid`),
  KEY `transfer_passwordencoding` (`password_encoding`),
  KEY `Transfers_user_email` (`user_email`),
  CONSTRAINT `Transfers_userid` FOREIGN KEY (`userid`) REFERENCES `UserPreferences` (`id`) ON DELETE CASCADE,
  CONSTRAINT `transfer_passwordencoding` FOREIGN KEY (`password_encoding`) REFERENCES `DBConstantPasswordEncodings` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2712301 DEFAULT CHARSET=utf8
```

**Comment by WebSpider** [comment] 2022-04-13 14:01
https://dev.mysql.com/doc/refman/5.7/en/charset.html

It used to be a mysql default

**Comment by madsi1m** [comment] 2022-05-19 06:42
Will future filesender versions have a check+migration to utf8 on the CHARACTER SET?

**Comment by monkeyiq** [comment] 2022-05-19 07:39
It seems like going latin1 to utf8 should be able to be done fairly painlessly. Before modifying the database.php to make it happen it would be a good idea to verify that it doesn't require a larger amount of processing.

I think it is a good idea to update the database.php to migrate to utf8 and would like to make a PR to do that.

**Comment by monkeyiq** [comment] 2022-07-14 06:36
I have updated the database.php to warn if things are not utf8mb4 with an override to continue anyway.

**Comment by WebSpider** [comment] 2022-07-14 06:59
I'm aware of installs that have included an ORM similar to sqlalchemy to manage the schema, migrations and inherit broad database support that comes from it.

This may be a solution here as well, but the path to it will take some time

**Comment by monkeyiq** [comment] 2022-07-16 04:26
It is probably a good idea to use a dedicated ORM library. Though there have been some interesting issues even on specific mariadb versions which might still be bumped into using an ORM.

In the meantime I have been trying to clean up the schema itself over the years. Using secondary indexes, moving to synthetic keys in some cases, once the former is done being able to add foreign keys referencing that table. Also having enum types that are database backed so that new enums can be added in the code and appear in the database as well so that RI can be maintained at the database level.

I think the time to clean up the schema and add these features may be useful when eventual migration to an ORM is considered as FKs for example are likely expected by the ORM.

**Comment by madsi1m** [comment] 2022-10-14 04:15
We have upgraded to 2.37 and the issue is resolved.

For anyone else who has this issue here is what we did, might have been a little extreme but it worked:

Before calling the db migration script we did a full export, dropped the tables and views and changed the defaults:
```
ALTER DATABASE filesender COLLATE = 'utf8mb4_bin';
```
Then reimported the db:
```
cat filesender.backup.sql | sed -e 's/ CHARSET=utf8;/ CHARSET=utf8mb4;/' -e 's/ CHARACTER SET latin1//' -e 's/utf8_general_ci/utf8mb4_bin/' -e 's/= utf8 \*\//= utf8mb4 *\//' -e 's/utf8)/utf8mb4)/g' -e 's/SET character_set_client = utf8;/SET character_set_client = utf8mb4;/' -e 's/ mediumint(8) / int(10) /' | grep -v "TType_TID_AType_AID_IP_EVENT_Created" | mysql -uABC -p123 filesender
```
Then:
```
time php migration-drop-foreign-keys.php
time php database.php
```

**Closed by madsi1m** 2022-10-14 04:15 UTC

**Comment by madsi1m** [comment] 2022-10-26 04:10
Thanks @WebSpider, no need, our issue is that the database.php when trying to convert would hit a timeout on the db and fail, which is why we did an export/import (with some nasty sed commands)

We were also on the 2beta or earlier db also.
