### ISSUE TITLE
WebPush is not notified only the first time on Safari

### ISSUE THREAD

**Issue by makinog3** [filesender/filesender#1429] opened 2023-04-11 10:43 UTC
Safari 16 on macOS Ventura is supported WebPush notification.
However, in the implementation of FileSender when a file upload is completed, it is not notified only the first time. It will be notified after the second time.

**Comment by monkeyiq** [comment] 2023-04-16 05:41
I will have to try to get access to a mac again to diagnose this.

**Comment by makinog3** [comment] 2023-04-16 05:46
@monkeyiq My primary development environment is macOS and I can help to develop(test) it.

**Comment by monkeyiq** [comment] 2023-04-17 23:02
I am assuming this issue is about the Notification API
https://developer.mozilla.org/en-US/docs/Web/API/notification

rather than to WebPush notification
https://developer.mozilla.org/en-US/docs/Web/API/Push_API

FileSender can use the Notification API if the transfer option is enabled to tell the user when an upload is complete. It currently does not use the WebPush API. Perhaps the WebPush API might be useful to notify a user if they are logged in an somebody uploads a file to them, but that is another story.

**Comment by monkeyiq** [comment] 2023-04-17 23:03
I will hopefully work something out to get easier access to osx for debugging such issues.

**Comment by monkeyiq** [comment] 2023-04-17 23:28
If you would like to dig into this the notification.js file would be where I would start. The `ask()` should be getting permission to show notification and the `notify()` method is called to deliver a message. I would first check that these are called (and complete ok) using something like console.log() against how they work in a chrome run.

https://github.com/filesender/filesender/blob/development/www/js/notification.js

It seems ask() is getting permission if the notifications are being shown after file1. IIRC Safari should ask for permission to notify before the file upload is started. It might be possible if the file is local and small that the first upload is completed before `this.available` is set to true in the `handlePermission` callback? If that is the case maybe `notify` would have to do something like calling itself after a delay a number of times to check if permission has been granted yet.

Adding a console.log() to the short out case in notify() will tell us if the above is the case and a fix might be worked on for it...
https://github.com/filesender/filesender/blob/defbf139675d167d1caf81433c1256c47f29781a/www/js/notification.js#L108

**Comment by meijer** [comment] 2023-04-18 04:25
> I will hopefully work something out to get easier access to osx for debugging such issues.

There are some mac-as-a-service providers out there, e.g.:
https://www.oakhost.net/mac-mini-hosting (monthly rent)
https://checkout.macincloud.com/ ($4/day for short term) 
or AWS, but if I understand it correctly that requires a 24 hour reservation of a dedicated host (https://aws.amazon.com/ec2/dedicated-hosts/pricing/ & https://aws.amazon.com/blogs/aws/use-amazon-ec2-m1-mac-instances-to-build-test-macos-ios-ipados-tvos-and-watchos-apps/)

**Comment by monkeyiq** [comment] 2023-04-19 23:12
I am guessing this becomes wanting to support push notifications from the server to the web page.

**Comment by makinog3** [comment] 2023-04-20 12:52
> Adding a console.log() to the short out case in notify() will tell us if the above is the case and a fix might be worked on for it...

I tried it:

```
    notify: function( title, msg, image ) {
        console.log("notify(): this.available=" + this.available);
        if( !this.available ) {
            return;
        }
```

Safari:
`[Log] notify(): this.available=false (notification.js, line 107)`

Chrome:
`notification.js:107 notify(): this.available=true`

**Comment by monkeyiq** [comment] 2023-04-21 05:36
I made https://github.com/filesender/filesender/pull/1444 which might resolve the issue. Certainly if I increase the delay in the setTimeout() to 10 seconds and do an upload Chrome sits there and after the allotted time it will show me the delayed notificaiton. Hopefully it does the same thing on Safari. Though in the PR the timeout is 100ms so it should happen as soon as Safari resolves the permission promise.

Please let me know if that helps things.

**Comment by makinog3** [comment] 2023-04-21 06:49
I have tried https://github.com/filesender/filesender/pull/1444, but not show the notification.
And I have tried using a large file(> 10MB) and spent several seconds, but not show it, too.

**Comment by monkeyiq** [comment] 2023-04-21 10:58
I added some more debug messages to the PR and pushed those changes. https://github.com/filesender/filesender/pull/1444/commits/7675f80bb0fc629ed41bbd9171606935d3011f12 Thanks for testing these debug tests!

I think if it was a race for a small file it would need to be a much larger file to avoid notifying too soon. Though the code asks for permission when you are still on the upload page before you click "send". So a race should be quite hard unless the promise was delayed by *a lot*.

At least in the new update I made we will see if the `handlePermission()` is being called in Safari there or not.

**Comment by makinog3** [comment] 2023-04-21 12:02
The debug messages were not logged(a larger file).

```
[Log] [8:58:39 PM] Transfer created, staring upload (ui.js, line 51)
[Log] [8:58:39 PM] [terasender driver] terasender.start(top)   mode 1 (ui.js, line 51)
[Log] [8:58:39 PM] [terasender driver] terasender.start(top) status  (ui.js, line 51)
[Log] [8:58:39 PM] [terasender driver] Starting transfer 331 with 1 files (12691015 bytes) (ui.js, line 51)
[Log] [8:58:39 PM] [terasender driver] Worker 0 created (ui.js, line 51)
[Log] [8:58:39 PM] [terasender driver] Worker 1 created (ui.js, line 51)
[Log] [8:58:39 PM] [terasender driver] Worker 2 created (ui.js, line 51)
[Log] [8:58:39 PM] [terasender driver] Worker 3 created (ui.js, line 51)
[Log] [8:58:39 PM] [terasender driver] Worker 4 created (ui.js, line 51)
[Log] [8:58:39 PM] [terasender worker:4] Requesting job (ui.js, line 51)
[Log] [8:58:39 PM] [terasender driver] Giving job to worker:4 (ui.js, line 51)
[Log] [8:58:39 PM] [terasender driver] allocateJob(top) mode:1 (ui.js, line 51)
[Log] [8:58:39 PM] [terasender driver] Found job file:388[0...5242880] (ui.js, line 51)
[Log] [8:58:39 PM] [terasender worker:1] Requesting job (ui.js, line 51)
[Log] [8:58:39 PM] [terasender driver] Giving job to worker:1 (ui.js, line 51)
[Log] [8:58:39 PM] [terasender driver] allocateJob(top) mode:1 (ui.js, line 51)
[Log] [8:58:39 PM] [terasender driver] Found job file:388[5242880...10485760] (ui.js, line 51)
[Log] [8:58:39 PM] [terasender worker:0] Requesting job (ui.js, line 51)
[Log] [8:58:39 PM] [terasender driver] Giving job to worker:0 (ui.js, line 51)
[Log] [8:58:39 PM] [terasender driver] allocateJob(top) mode:1 (ui.js, line 51)
[Log] [8:58:39 PM] [terasender driver] Found job file:388[10485760...12691015] (ui.js, line 51)
[Log] [8:58:39 PM] [terasender worker:2] Requesting job (ui.js, line 51)
[Log] [8:58:39 PM] [terasender driver] Giving job to worker:2 (ui.js, line 51)
[Log] [8:58:39 PM] [terasender driver] allocateJob(top) mode:1 (ui.js, line 51)
[Log] [8:58:39 PM] [terasender driver] No jobs remaining, terminating (ui.js, line 51)
[Log] [8:58:39 PM] [terasender worker:3] Requesting job (ui.js, line 51)
[Log] [8:58:39 PM] [terasender driver] Giving job to worker:3 (ui.js, line 51)
[Log] [8:58:39 PM] [terasender driver] allocateJob(top) mode:1 (ui.js, line 51)
[Log] [8:58:39 PM] [terasender driver] No jobs remaining, terminating (ui.js, line 51)
[Log] [8:58:39 PM] [terasender worker:4] Starting job file:388[0...5242880] (ui.js, line 51)
[Log] [8:58:39 PM] [terasender worker:1] Starting job file:388[5242880...10485760] (ui.js, line 51)
[Log] [8:58:39 PM] [terasender worker:0] Starting job file:388[10485760...12691015] (ui.js, line 51)
[Log] [8:58:39 PM] [terasender worker:4] Job file:388[0...5242880] is 100.0% done 5242880/5242880 (ui.js, line 51)
[Log] [8:58:39 PM] [terasender worker:4] Worker job progressed (ui.js, line 51)
[Log] [8:58:39 PM] Uploading filesender.tgz (12691015 bytes) : 41.31% (ui.js, line 51)
[Log] ending() only_one_pbkdf2_process: false (crypto_app.js, line 14)
[Log] pbkdf2dialog onPBKDF2Over() (crypto_app.js, line 14)
[Log] pbkdf2dialog onPBKDF2AllEnded() (crypto_app.js, line 14)
[Log] [8:58:39 PM] [terasender worker:0] Job file:388[10485760...12691015] is 100.0% done 2205255/2205255 (ui.js, line 51)
[Log] [8:58:39 PM] [terasender worker:0] Worker job progressed (ui.js, line 51)
[Log] [8:58:39 PM] Uploading filesender.tgz (12691015 bytes) : 58.69% (ui.js, line 51)
[Log] [8:58:39 PM] [terasender worker:1] Job file:388[5242880...10485760] is 80.0% done 4194304/5242880 (ui.js, line 51)
[Log] [8:58:39 PM] [terasender worker:1] Worker job progressed (ui.js, line 51)
[Log] [8:58:39 PM] Uploading filesender.tgz (12691015 bytes) : 91.74% (ui.js, line 51)
[Log] [8:58:40 PM] [terasender worker:1] Job file:388[5242880...10485760] is 100.0% done 5242880/5242880 (ui.js, line 51)
[Log] [8:58:40 PM] [terasender worker:1] Worker job progressed (ui.js, line 51)
[Log] [8:58:40 PM] Uploading filesender.tgz (12691015 bytes) : 100.00% (ui.js, line 51)
[Log] [8:58:41 PM] [terasender worker:4] Executed job file:388[0...5242880] (ui.js, line 51)
[Log] [8:58:41 PM] [terasender worker:4] Worker executed job (ui.js, line 51)
[Log] [8:58:41 PM] Uploading filesender.tgz (12691015 bytes) : 100.00% (ui.js, line 51)
[Log] [8:58:41 PM] [terasender driver] Giving job to worker:4 (ui.js, line 51)
[Log] [8:58:41 PM] [terasender driver] allocateJob(top) mode:1 (ui.js, line 51)
[Log] [8:58:41 PM] [terasender driver] No jobs remaining, terminating (ui.js, line 51)
[Log] [8:58:41 PM] [terasender worker:1] Executed job file:388[5242880...10485760] (ui.js, line 51)
[Log] [8:58:41 PM] [terasender worker:1] Worker executed job (ui.js, line 51)
[Log] [8:58:41 PM] Uploading filesender.tgz (12691015 bytes) : 100.00% (ui.js, line 51)
[Log] [8:58:41 PM] [terasender driver] Giving job to worker:1 (ui.js, line 51)
[Log] [8:58:41 PM] [terasender driver] allocateJob(top) mode:1 (ui.js, line 51)
[Log] [8:58:41 PM] [terasender driver] No jobs remaining, terminating (ui.js, line 51)
[Log] [8:58:41 PM] [terasender worker:0] Executed job file:388[10485760...12691015] (ui.js, line 51)
[Log] [8:58:41 PM] [terasender worker:0] Worker executed job (ui.js, line 51)
[Log] [8:58:41 PM] File filesender.tgz (12691015 bytes) uploaded (ui.js, line 51)
[Log] [8:58:41 PM] [terasender driver] Giving job to worker:0 (ui.js, line 51)
[Log] [8:58:41 PM] [terasender driver] allocateJob(top) mode:1 (ui.js, line 51)
[Log] [8:58:41 PM] [terasender driver] No jobs remaining, terminating (ui.js, line 51)
[Log] [8:58:41 PM] Transfer 331 (12691015 bytes) complete, took 2.674s (ui.js, line 51)
```

**Comment by monkeyiq** [comment] 2023-04-22 03:30
It seems that the `ask()` method is not getting to that point. I added some info at the top of `ask` to see why https://github.com/filesender/filesender/pull/1444/commits/176b619d199e5c6be384fb8dfae9dd095c6636cc

**Comment by makinog3** [comment] 2023-04-22 04:40
```
[Log] AAA ask() (notification.js, line 53)
[Log] AAA ask() force – false (notification.js, line 54)
[Log] AAA ask() asked  – false (notification.js, line 55)
[Log] AAA ask() Notification.permission  – "default" (notification.js, line 56)
[Log] ask() in the else part. (notification.js, line 100)
[Log] ask() in checkNotificationPromise() part. (notification.js, line 102)
[Error] Notification prompting can only be done from a user gesture.
	ask (notification.js:103)
	(anonymous function) (upload_page.js:1705)
	dispatch (jquery.min.js:2:43342)
[Log] handlePermission() have result:  – "default" (notification.js, line 78)
[Log] mouseenter href=https://filesender-dev.nii.ac.jp/?s=upload# (manualscan.js, line 244)
[Log] [1:37:25 PM] Creating transfer (ui.js, line 51)
[Log] clear rating time out (manualscan.js, line 290)
[Log] [1:37:25 PM] Transfer created, staring upload (ui.js, line 51)
[Log] [1:37:25 PM] [terasender driver] terasender.start(top)   mode 1 (ui.js, line 51)
[Log] [1:37:25 PM] [terasender driver] terasender.start(top) status  (ui.js, line 51)
[Log] [1:37:25 PM] [terasender driver] Starting transfer 332 with 1 files (12691015 bytes) (ui.js, line 51)
[Log] [1:37:25 PM] [terasender driver] Worker 0 created (ui.js, line 51)
[Log] [1:37:25 PM] [terasender driver] Worker 1 created (ui.js, line 51)
[Log] [1:37:25 PM] [terasender driver] Worker 2 created (ui.js, line 51)
[Log] [1:37:25 PM] [terasender driver] Worker 3 created (ui.js, line 51)
[Log] [1:37:25 PM] [terasender driver] Worker 4 created (ui.js, line 51)
[Log] [1:37:26 PM] [terasender worker:3] Requesting job (ui.js, line 51)
[Log] [1:37:26 PM] [terasender driver] Giving job to worker:3 (ui.js, line 51)
[Log] [1:37:26 PM] [terasender driver] allocateJob(top) mode:1 (ui.js, line 51)
[Log] [1:37:26 PM] [terasender driver] Found job file:389[0...5242880] (ui.js, line 51)
[Log] [1:37:26 PM] [terasender worker:4] Requesting job (ui.js, line 51)
[Log] [1:37:26 PM] [terasender driver] Giving job to worker:4 (ui.js, line 51)
[Log] [1:37:26 PM] [terasender driver] allocateJob(top) mode:1 (ui.js, line 51)
[Log] [1:37:26 PM] [terasender driver] Found job file:389[5242880...10485760] (ui.js, line 51)
[Log] [1:37:26 PM] [terasender worker:2] Requesting job (ui.js, line 51)
[Log] [1:37:26 PM] [terasender driver] Giving job to worker:2 (ui.js, line 51)
[Log] [1:37:26 PM] [terasender driver] allocateJob(top) mode:1 (ui.js, line 51)
[Log] [1:37:26 PM] [terasender driver] Found job file:389[10485760...12691015] (ui.js, line 51)
[Log] [1:37:26 PM] [terasender worker:1] Requesting job (ui.js, line 51)
[Log] [1:37:26 PM] [terasender driver] Giving job to worker:1 (ui.js, line 51)
[Log] [1:37:26 PM] [terasender driver] allocateJob(top) mode:1 (ui.js, line 51)
[Log] [1:37:26 PM] [terasender driver] No jobs remaining, terminating (ui.js, line 51)
[Log] [1:37:26 PM] [terasender worker:0] Requesting job (ui.js, line 51)
[Log] [1:37:26 PM] [terasender driver] Giving job to worker:0 (ui.js, line 51)
[Log] [1:37:26 PM] [terasender driver] allocateJob(top) mode:1 (ui.js, line 51)
[Log] [1:37:26 PM] [terasender driver] No jobs remaining, terminating (ui.js, line 51)
[Log] [1:37:26 PM] [terasender worker:3] Starting job file:389[0...5242880] (ui.js, line 51)
[Log] [1:37:26 PM] [terasender worker:4] Starting job file:389[5242880...10485760] (ui.js, line 51)
[Log] [1:37:26 PM] [terasender worker:2] Starting job file:389[10485760...12691015] (ui.js, line 51)
[Log] [1:37:26 PM] [terasender worker:3] Job file:389[0...5242880] is 100.0% done 5242880/5242880 (ui.js, line 51)
[Log] [1:37:26 PM] [terasender worker:3] Worker job progressed (ui.js, line 51)
[Log] [1:37:26 PM] Uploading filesender.tgz (12691015 bytes) : 41.31% (ui.js, line 51)
[Log] ending() only_one_pbkdf2_process: false (crypto_app.js, line 14)
[Log] pbkdf2dialog onPBKDF2Over() (crypto_app.js, line 14)
[Log] pbkdf2dialog onPBKDF2AllEnded() (crypto_app.js, line 14)
[Log] [1:37:26 PM] [terasender worker:2] Job file:389[10485760...12691015] is 100.0% done 2205255/2205255 (ui.js, line 51)
[Log] [1:37:26 PM] [terasender worker:2] Worker job progressed (ui.js, line 51)
[Log] [1:37:26 PM] Uploading filesender.tgz (12691015 bytes) : 58.69% (ui.js, line 51)
[Log] [1:37:26 PM] [terasender worker:4] Job file:389[5242880...10485760] is 100.0% done 5242880/5242880 (ui.js, line 51)
[Log] [1:37:26 PM] [terasender worker:4] Worker job progressed (ui.js, line 51)
[Log] [1:37:26 PM] Uploading filesender.tgz (12691015 bytes) : 100.00% (ui.js, line 51)
[Log] [1:37:27 PM] [terasender worker:3] Executed job file:389[0...5242880] (ui.js, line 51)
[Log] [1:37:27 PM] [terasender worker:3] Worker executed job (ui.js, line 51)
[Log] [1:37:27 PM] Uploading filesender.tgz (12691015 bytes) : 100.00% (ui.js, line 51)
[Log] [1:37:27 PM] [terasender driver] Giving job to worker:3 (ui.js, line 51)
[Log] [1:37:27 PM] [terasender driver] allocateJob(top) mode:1 (ui.js, line 51)
[Log] [1:37:27 PM] [terasender driver] No jobs remaining, terminating (ui.js, line 51)
[Log] [1:37:27 PM] [terasender worker:4] Executed job file:389[5242880...10485760] (ui.js, line 51)
[Log] [1:37:27 PM] [terasender worker:4] Worker executed job (ui.js, line 51)
[Log] [1:37:27 PM] Uploading filesender.tgz (12691015 bytes) : 100.00% (ui.js, line 51)
[Log] [1:37:27 PM] [terasender driver] Giving job to worker:4 (ui.js, line 51)
[Log] [1:37:27 PM] [terasender driver] allocateJob(top) mode:1 (ui.js, line 51)
[Log] [1:37:27 PM] [terasender driver] No jobs remaining, terminating (ui.js, line 51)
[Log] [1:37:27 PM] [terasender worker:2] Executed job file:389[10485760...12691015] (ui.js, line 51)
[Log] [1:37:27 PM] [terasender worker:2] Worker executed job (ui.js, line 51)
[Log] [1:37:27 PM] File filesender.tgz (12691015 bytes) uploaded (ui.js, line 51)
[Log] [1:37:27 PM] [terasender driver] Giving job to worker:2 (ui.js, line 51)
[Log] [1:37:27 PM] [terasender driver] allocateJob(top) mode:1 (ui.js, line 51)
[Log] [1:37:27 PM] [terasender driver] No jobs remaining, terminating (ui.js, line 51)
[Log] [1:37:27 PM] Transfer 332 (12691015 bytes) complete, took 1.809s (ui.js, line 51)
```

**Comment by monkeyiq** [comment] 2023-04-24 00:52
It is interesting that it is returning a denial to ask for notifications and at the same time seems to be asking and allowing it (for the 2nd notification to get through).

```
[Log] ask() in checkNotificationPromise() part. (notification.js, line 102)
[Error] Notification prompting can only be done from a user gesture.
	ask (notification.js:103)
	(anonymous function) (upload_page.js:1705)
	dispatch (jquery.min.js:2:43342)
```

**Comment by monkeyiq** [comment] 2023-04-24 01:09
It might work with https://github.com/filesender/filesender/pull/1448.

**Comment by makinog3** [comment] 2023-04-24 01:53
I tried it, and the notification showed up the first time as well!
Thank you so much!!

**Comment by monkeyiq** [comment] 2023-04-24 11:18
Excellent! I will do some more validation on Chrome and Firefox in preparation for a merge :)

**Comment by monkeyiq** [comment] 2023-04-24 22:54
Merged. Will be in the next release. 

Thanks for the debugging feedback!

**Comment by monkeyiq** [comment] 2023-06-13 06:33
I'll close this issue now I think. If there is a regression in the release please let me know. Thank you for reporting the issue and testing / verifying the fix :)

**Closed** 2023-06-13 06:34 UTC
Labels: fix merged
