### ISSUE TITLE
FilesenderRestClient.class.php help?

### ISSUE THREAD

**Issue by madsi1m** [filesender/filesender#22] opened 2017-02-03 00:55 UTC
Hi All,

We have a user who would like to use the API but is getting "EXCEPTION [0] Http error 500".

I looked in our logs and have this:

> 03-Feb-2017 00:42:17 Europe/London] PHP Fatal error:  Call to a member function exists() on null in /www/filesender-2.0/classes/rest/endpoints/RestEndpointTransfer.class.php on line 355
> [03-Feb-2017 00:42:17 Europe/London] PHP Stack trace:
> [03-Feb-2017 00:42:17 Europe/London] PHP   1. {main}() /www/filesender-2.0/www/rest.php:0
> [03-Feb-2017 00:42:17 Europe/London] PHP   2. RestServer::process() /www/filesender-2.0/www/rest.php:37
> [03-Feb-2017 00:42:17 Europe/London] PHP   3. call_user_func_array:{/www/filesender-2.0/classes/rest/RestServer.class.php:237}() /www/filesender-2.0/classes/rest/RestServer.class.php:237
> [03-Feb-2017 00:42:17 Europe/London] PHP   4. RestEndpointTransfer->post() /www/filesender-2.0/classes/rest/RestServer.class.php:237

The code the user has written (slightly changed for testing) is as follows:
```
<?php
require_once 'FilesenderRestClient.class.php';
try {
    $c = new FilesenderRestClient('https://cloudstor.aarnet.edu.au/sender/rest.php', 'user', 'username', 'apikey');

    print_r($c->getInfo());

    $c->sendFiles('someonereal@email','someonereal@email','/tmp/x.txt','someonereal@email',null,null,1486082270,null);
    print_r($c->getInfo());
} catch(Exception $e) {
    echo 'EXCEPTION ['.$e->getCode().'] '.$e->getMessage();
}

?>
```

And this is the output:
```
stdClass Object
(
    [url] => https://cloudstor.aarnet.edu.au/sender/
    [name] => CloudStor Sender
    [logon_url] => /simplesaml/module.php/core/as_login.php?AuthId=default-sp&ReturnTo=__target__
    [upload_chunk_size] => 12582912
)
EXCEPTION [0] Http error 500
```

Any ideas/pointers?

**Comment by jornane** [comment] 2017-02-03 08:34
When not setting any options, don't pass `null` but an empty array instead (`[]`).

Maybe the FilesenderRestClient class should be patched to warn about this, or to sanitize input so that this precondition is met, even when the user provides `null`.

**Comment by madsi1m** [comment] 2017-02-06 05:23
Strange, same error when sending array()

**Comment by jornane** [comment] 2017-02-07 16:46
Then something else is wrong. Have you checked the server logs? Sadly, the REST client doesn't show any errors returned from the server, but we have used the REST API at various occasions at UNINETT.

**Comment by madsi1m** [comment] 2017-02-08 04:18
On my dev box:

PHP Notice:  Undefined index: Location in /www/filesender-2.0/scripts/client/FilesenderRestClient.class.php on line 211

Notice: Undefined index: Location in /www/filesender-2.0/scripts/client/FilesenderRestClient.class.php on line 211
PHP Notice:  Trying to get property of non-object in /www/filesender-2.0/scripts/client/FilesenderRestClient.class.php on line 452


What is Location?

**Comment by jornane** [comment] 2017-02-13 16:37
The Location error seems like some sloppyness in the client, but it shouldn't affect the result.
The ` Trying to get property of non-object` error is a bit more serious, though. You may need some print-debugging there.

**Comment by madsi1m** [comment] 2017-03-22 02:40
fixed in https://github.com/filesender/filesender/pull/43
code did not follow th doc on how to do it

**Comment by jornane** [comment] 2017-03-24 16:09
If the issue is fixed, this ticket can be closed?

**Comment by madsi1m** [comment] 2017-03-26 22:45
It can be closed once https://github.com/filesender/filesender/pull/43 is pulled into master

**Comment by monkeyiq** [comment] 2017-07-13 04:30
it seems #43 was committed in two parts https://github.com/filesender/filesender/pull/43#issuecomment-295736585 

So does that mean this issues is also solved or still to do?

**Comment by jornane** [comment] 2017-07-13 08:33
When that was merged, there was a strange conditional in [RestEndpointTransfer.class.php](https://github.com/filesender/filesender/pull/43/commits/23c0284e7257b88b510f0f4d38452a40addc6663) (two different ways to set `$value`)

That seems wrong, and it would be wise to find out why the variable can be formatted in different ways.

However, this code was removed again when [RestEndpointTransfer.class.php](https://github.com/filesender/filesender/pull/34/files#diff-6afcec4cdb04be9dee1fc62bf3eca799) in #34 was merged. If that merge didn't break this ticket by regression, I think we can close this ticket.

**Comment by WebSpider** [comment] 2020-03-30 08:49
@jornane is this issue still relevant? If not, please feel free to close the issue :)

**Comment by monkeyiq** [comment] 2020-05-15 00:39
I might close this as it has been idle for a long time. Please reopen if it is still in need of attention.

**Closed by monkeyiq** 2020-05-15 00:39 UTC
Labels: question
