### ISSUE TITLE
Windows 7 and IE11 bad interaction on upload start

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#355] opened 2018-07-03 07:47 UTC
Sometimes on Windows 7 and IE11 pressing start for a transfer does nothing. 

I am not sure if this happens every time for a machine or only sometimes. It is hard to reproduce.

This was originally reported by William van Santen.

**Comment by monkeyiq** [comment] 2018-07-03 07:50
This would be a good use case for the new clientlogs feature of 2.1. Grabbing a nice section of lines from the client. If no dialog box comes up (eventually) when the issue presents itself so the upload logs button is available I can add one to the transfers page in order to test this issue.

I am wondering if anybody has a setup like the above and an reproduce the issue in a somewhat reliable way? Can somebody who can trigger the issue share access to a virtual environment where I can take a look to try to determine what is going on?

**Comment by monkeyiq** [comment] 2018-07-03 08:06
If anyone gets reports from users about this issue, it would be wonderful if they could also ask if the same people always have a problem with the upload or if it is only sometimes. This would rule out a suspicion that I have. Apparently at times browser config can limit what happens and can limit web worker tasks (that TeraSender uses). But if this is the problem then it would stop the same person from uploading all the time and not effect other folks.

**Comment by jornane** [comment] 2018-07-14 18:55
All our users complaining about this, are trying to upload using a guest voucher. Not using a login session. Maybe this bug can be reproduced reliably by trying to upload form a guest voucher?

**Comment by monkeyiq** [comment] 2018-07-15 00:33
This is very useful information. I had thought that IE11 didn't like the TeraSender code or there was some interaction in that codepath. So this helps narrow things down a little bit.

If anybody with access to this win/ie combination can see if a guest voucher does reproduce the bug reliably that would be wonderful.

**Comment by Veredior** [comment] 2018-09-26 07:30
Since we upgrade our FileSender from 2.0-beta to 2.3, all uploads on IE11 failed on start, on the first chunk.

**Comment by WebSpider** [comment] 2023-03-28 10:23
@monkeyiq given that Win7 and IE11 are unsupported by the vendor, we may want to consider closing this.

**Closed** 2023-09-19 12:57 UTC
Labels: help wanted, feedback-needed
