### ISSUE TITLE
Edge, crypto not working

### ISSUE THREAD

**Issue by madsi1m** [filesender/filesender#628] opened 2019-09-03 06:21 UTC
In Edge,

It seems that crypto.subtle.importKey does not run its .then( and gets stuck.

Might be because we are using one of these cryptos?
![image](https://user-images.githubusercontent.com/11512591/64148507-d0686780-ce66-11e9-992b-33f48eedb430.png)

**Comment by monkeyiq** [comment] 2019-09-04 13:16
This relates to https://github.com/filesender/filesender/issues/338 which lead to the introduction of key_version = 1 to better handle key setup in FileSender. I see the same issue here on Edge + Windows10. If I set in the config the following to use the older key version then encryption works in Edge. 

```
$config['encryption_key_version_new_files'] = 0;
```

From searching around it seems that using PBKDF2 in Edge might be the cause. See for example, https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9259365/

**Comment by madsi1m** [comment] 2019-09-05 00:33
should 0 then be the default?

**Comment by monkeyiq** [comment] 2019-09-07 00:19
As maintainer of the project I will ask the filesender board what the choice for the default should be for crypto version in the configdefaults for this setting. 

From a usability perspective, key version 1 does not work with Microsoft browsers. Key version 0 works right back to IE11. With more research key version 1 might in the future be able to work on Edge. I thought it was working on Edge but have only recently got ready access to a windows 10 machine for testing.

From a crypto perspective, version 1 should provide better keys for user supplied passwords. Specifically due to how they are translated from a string into a key using hashing and per transfer salt value. With the recent update to random passwords they already contain plenty of entropy so the difference in key version 0 or 1 is less for generated passwords. As mentioned by a crypto expert in the final paragraph of https://github.com/filesender/filesender/pull/375#issuecomment-439160499 hashing is not needed on randomly generated keys.

If a person is interested in the crypto they are likely to already be leaning toward using random passwords. Some have advocated for only allowing random passwords. Personally I think usability of the system may suffer too much in that case.

Hopefully the 2nd and 3rd paragraphs of this comment provide insight into this setting to allow for a per site choice to me made. As the key version is stored for existing transfers you should be able to change to a different value which is used in newly created transfers. I have tested this and had feedback from an NREN who has switched from version 1 to version 0 for new files while allowing existing files to still be decrypted. I always recommend a retest of that just to be sure. This key version change testing is something I have slated to add to the CI system shortly.

As an aside, it is a tempting idea to try to use key version 0 if somebody is uploading using IE etc but that is an incomplete solution as somebody might upload using Chrome or Firefox and not know if they are sending the file to somebody using an MS browser.

**Comment by monkeyiq** [comment] 2019-09-09 00:15
Specifically, the CI tests now using https://github.com/filesender/filesender/pull/637

**Comment by monkeyiq** [comment] 2020-01-22 23:17
This should be working in Edge for AES-CBC as of https://github.com/filesender/filesender/releases/tag/master-filesender-2.14. Unfortunately there seem to be more issues with GCM support in Edge.

To clarify, key version 0 and 1 should now work in edge.

**Comment by WebSpider** [comment] 2022-01-16 15:23
I think with Edge moving to Chromium-based, this issue is no longer relevant ?

**Comment by monkeyiq** [comment] 2022-01-19 22:11
It is very fortunate that the Chromium based update is rolled out in windows updates. I notice that my testing win10 machine is now chromium backed so I'll do another round of testing on that shortly.

Depending on what the FileSender board wishes I may have to arrange a win10-edge-non-chromium for legacy testing :(

**Comment by monkeyiq** [comment] 2023-01-29 07:44
Is anyone still having issues in Edge/Chromium with this?

**Closed** 2023-04-16 06:29 UTC
Labels: feedback-needed
