### ISSUE TITLE
fedauth receipt validation

### ISSUE THREAD

**Issue by leifj** [filesender/filesender#914] opened 2021-02-15 10:10 UTC
For some use-cases it is useful to be able to require that the recipient authenticate using something similar to what the sender used - i.e fedauth in most cases. This should/could be an option selected as an advanced option when creating the transfer.

**Comment by peter-** [comment] 2021-02-19 16:08
Is `Authenticate to download` sufficient, though? Depending on the number of IDPs hooked up to your FileSender instance (or the difficulty of getting an account at any one of them, e.g. self-registering at one of them) authenticating with _any_ account at _any_ configured IDP may not be adding significant protection?  
It'd be a (necssary) first step, though, I agree.

Or are we straight into authorisation here, i.e., specifying who exactly should be allowed to download the transfer (which would be much harder, probably needing a UI to assist people in select from existing FileSender users, assuming "discoverable" data about those subjects is available, e.g. "recognisable" identifiers in use, displayName beint set, etc.). As we know from deploying Confluence etc. that also has other issues, such as not being able to authorise someone who has not logged in yet (or whose local data has meanwhile expired, given FileSenders transient nature) or the privacy issue of evey user of the system then being able to see data about every other user of the system, etc.

**Comment by leifj** [comment] 2021-04-26 13:52
I think authenticate-to-download is sufficient for most usecases.

**Comment by WebSpider** [comment] 2022-01-16 15:13
If the issue is solved for you, please don't forget to close it ;-)

**Comment by monkeyiq** [comment] 2023-01-29 07:53
If this is still an active issue please reopen this or start a new issue. Thank you.

**Closed by monkeyiq** 2023-01-29 07:53 UTC
