### ISSUE TITLE
Change saml data

### ISSUE THREAD

**Issue by kenroyandfamily** [filesender/filesender#1273] opened 2022-06-23 19:43 UTC
clidownload.php uses "Auth::user()->saml_user_identification_uid", which translates to "samaccountname" in our active directory.  We would like this to resolve to the user's email address instead.  

We could just use "Auth::user()->email_addresses[0];", but we prefer to have this handled in the config.php (or some other simplesaml file) .  I've been attempting to do this in config.php for simplesaml, but I have been unsuccessful.

**Comment by thijskh** [comment] 2022-06-23 19:48
Hi, you are looking for these settings in Filesender's config.php:
https://github.com/filesender/filesender/blob/0a4e6087fc8b59df128f68712cfbb6b67e98d130/config/config_sample.php#L105-L118

In the third one of those you set whatever SimpleSAML attribute you want the uid to be.

**Comment by kenroyandfamily** [comment] 2022-06-23 19:51
Bingo!  Thanks for the incredibly quick response.  I thought I looked there and tried that but perhaps I made a mistake.  

Thanks!

**Comment by kenroyandfamily** [comment] 2022-06-23 20:02
But I do have an issue with the filesender.py script.  It makes an assumption that the username is an email and so uses it both for "remote_user" and "mail from" fields.  But our AD setup doesn't use email addresses for usernames. 

We are currently just rewriting filesender.py to accommodate this, but prefer to not have to maintain this change for every new version of filesender.

Any thoughts on this?

**Comment by thijskh** [comment] 2022-06-23 20:25
I'm not familiar with the internals of that script but I'm quite certain that a PR improving this would be welcomed.

**Comment by kenroyandfamily** [comment] 2022-06-23 20:25
I actually rewrote it so I could submit it

**Comment by WebSpider** [comment] 2022-06-28 11:16
Please feel free to submit a PR for this!

**Comment by monkeyiq** [comment] 2022-07-06 06:05
@kenroyandfamily I am happy to take a look at a diff against filesender.py to see if something can be merged. Perhaps a new config.php setting to be able to select one functionality or the older?

**Comment by monkeyiq** [comment] 2022-07-06 06:06
Maybe we could have RFC: as a prefix on a PR that is partial or for comments on how we should resolve things.

**Comment by WebSpider** [comment] 2022-07-09 08:01
@monkeyiq personally I prefer to use github issue templates for this, also because it makes automated ticket handling with bots a lot easier.

Issue templates: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

Issue bots: many to be found in github marketplace

If this seems like a good way forward, I can set up some examples in a branch.

**Comment by monkeyiq** [comment] 2022-07-14 03:44
I have been thinking for a while having a script to collect apache, php, mysql/mariadb, postgresql, firefox, chrome versions from the local machine or settings in config.php (for database that is not on localhost) might be useful. This could allow reports to include that information without requiring folks to explicitly grab each piece each time.

**Comment by monkeyiq** [comment] 2022-07-14 03:56
I am creating a generate version script...

**Comment by monkeyiq** [comment] 2022-07-14 04:25
An initial generate info script is up at https://github.com/filesender/filesender/pull/1288

**Comment by monkeyiq** [comment] 2023-01-29 01:47
Hi, any thoughts on sharing your updated filesender.py script. Best to ask before anyone duplicates the effort :)

**Comment by KenRoy-Octo** [comment] 2023-01-29 03:01
Here's our version of filesender.  There are two parameters "userid" and "username".  "username" is used to postTransfer and should be an email address while "userid" is for logging in and can be a valid email address or not depending on your authentication user requirements.

`
#!/usr/bin/env python3
#
# FileSender www.filesender.org
#
# Copyright (c) 2009-2019, AARNet, Belnet, HEAnet, SURFnet, UNINETT
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# *   Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
# *   Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
# *   Neither the name of AARNet, Belnet, HEAnet, SURFnet and UNINETT nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import argparse
try:
  import requests
  import time
  from collections.abc import Iterable
  from collections.abc import MutableMapping
  import hmac
  import hashlib
  import urllib3
  import os
  import json
  import configparser
  from os.path import expanduser
except Exception as e:
  print(type(e))
  print(e.args)
  print(e)
  print('')
  print('ERROR: A required dependency is not installed, please check your')
  print('distribution packages or run something like the following')
  print('')
  print('pip3 install requests urllib3 ')
  exit(1)


urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

#settings
base_url = '[base_url]'
default_transfer_days_valid = 10
username = None
apikey = None
homepath = expanduser("~")
userid = None

config = configparser.ConfigParser()
config.read(homepath + '/.filesender/filesender.py.ini')
if 'system' in config:
  base_url = config['system'].get('base_url', '[base_url]')
  default_transfer_days_valid = int(config['system'].get('default_transfer_days_valid', 10))
if 'user' in config:
  username = config['user'].get('username')
  apikey = config['user'].get('apikey')






#argv
parser = argparse.ArgumentParser()
parser.add_argument("files", help="path to file(s) to send", nargs='+')
parser.add_argument("-v", "--verbose", action="store_true")
parser.add_argument("-i", "--insecure", action="store_true")
parser.add_argument("-p", "--progress", action="store_true")
parser.add_argument("-s", "--subject")
parser.add_argument("-m", "--message")
requiredNamed = parser.add_argument_group('required named arguments')

# if we have found these in the config file they become optional arguments
if username is None:
  requiredNamed.add_argument("-u", "--username", required=True)
else:
  parser.add_argument("-u", "--username")

if apikey is None:
  requiredNamed.add_argument("-a", "--apikey", required=True)
else:
  parser.add_argument("-a", "--apikey")

if userid is None:
  requiredNamed.add_argument("-c", "--userid", required=True)
else:
  parser.add_argument("-c", "--userid")


requiredNamed.add_argument("-r", "--recipients", required=True)
args = parser.parse_args()
debug = args.verbose
progress = args.progress
insecure = args.insecure

if args.username is not None:
  username = args.username

if args.apikey is not None:
  apikey = args.apikey

if args.userid is not None:
  userid = args.userid

#configs
try:
  response = requests.get(base_url+'/info', verify=True)
except requests.exceptions.SSLError as exc:
  if not insecure:
    print('Error: the SSL certificate of the server you are connecting to cannot be verified:')
    print(exc)
    print('For more information, please refer to https://www.digicert.com/ssl/. If you are absolutely certain of the identity of the server you are connecting to, you can use the --insecure flag to bypass this warning. Exiting...')
    sys.exit(1)
  elif insecure:
    print('Warning: Error: the SSL certificate of the server you are connecting to cannot be verified:')
    print(exc)
    print('Running with --insecure flag, ignoring warning...')
    response = requests.get(base_url+'/info', verify=False)
upload_chunk_size = response.json()['upload_chunk_size']

if debug:
  print('base_url          : '+base_url)
  print('username          : '+username)
  print('apikey            : '+apikey)
  print('upload_chunk_size : '+str(upload_chunk_size)+' bytes')
  print('recipients        : '+args.recipients)
  print('files             : '+','.join(args.files))
  print('insecure          : '+str(insecure))
  print('userid            : '+str(userid))

##########################################################################

def flatten(d, parent_key=''):
  items = []
  for k, v in d.items():
    new_key = parent_key + '[' + k + ']' if parent_key else k
    if isinstance(v, MutableMapping):
      items.extend(flatten(v, new_key).items())
    else:
      items.append(new_key+'='+v)
  items.sort()
  return items

def call(method, path, data, content=None, rawContent=None, options={}):
  data['remote_user'] = userid
  data['timestamp'] = str(round(time.time()))
  flatdata=flatten(data)
  signed = bytes(method+'&'+base_url.replace('https://','',1).replace('http://','',1)+path+'?'+('&'.join(flatten(data))), 'ascii')

  content_type = options['Content-Type'] if 'Content-Type' in options else 'application/json'

  inputcontent = None
  if content is not None and content_type == 'application/json':
    inputcontent = json.dumps(content,separators=(',', ':'))
    signed += bytes('&'+inputcontent, 'ascii')
  elif rawContent is not None:
    inputcontent = rawContent
    signed += bytes('&', 'ascii')
    signed += inputcontent

  #print(signed)
  bkey = bytearray()
  bkey.extend(map(ord, apikey))
  data['signature'] = hmac.new(bkey, signed, hashlib.sha1).hexdigest()

  url = base_url+path+'?'+('&'.join(flatten(data)))
  headers = {
    "Accept": "application/json",
    "Content-Type": content_type
  }
  response = None
  if method == "get":
    response = requests.get(url, verify=not insecure, headers=headers)
  elif method == "post":
    response = requests.post(url, data=inputcontent, verify=not insecure, headers=headers)
  elif method == "put":
    response = requests.put(url, data=inputcontent, verify=not insecure, headers=headers)
  elif method == "delete":
    response = requests.delete(url, verify=not insecure, headers=headers)

  if response is None:
    raise Exception('Client error')

  code = response.status_code
  #print(url)
  #print(inputcontent)
  #print(code)
  #print(response.text)

  if code!=200:
    if method!='post' or code!=201:
      raise Exception('Http error '+str(code)+' '+response.text)

  if response.text=="":
    raise Exception('Http error '+str(code)+' Empty response')

  if method!='post':
    return response.json()

  r = {}
  r['location']=response.headers['Location']
  r['created']=response.json()
  return r

def postTransfer(user_id, files, recipients, subject=None, message=None, expires=None, options=[]):

  if expires is None:
    expires = round(time.time()) + (default_transfer_days_valid*24*3600)

  to = [x.strip() for x in recipients.split(',')]

  return call(
    'post',
    '/transfer',
    {},
    {
      'from': user_id,
      'files': files,
      'recipients': to,
      'subject': subject,
      'message': message,
      'expires': expires,
      'aup_checked':1,
      'options': options
    },
    None,
    {}
  )

def putChunk(t, f, chunk, offset):
  return call(
    'put',
    '/file/'+str(f['id'])+'/chunk/'+str(offset),
    { 'key': f['uid'], 'roundtriptoken': t['roundtriptoken'] },
    None,
    chunk,
    { 'Content-Type': 'application/octet-stream' }
  )

def fileComplete(t,f):
  return call(
    'put',
    '/file/'+str(f['id']),
    { 'key': f['uid'], 'roundtriptoken': t['roundtriptoken'] },
    { 'complete': True },
    None,
    {}
  )

def transferComplete(transfer):
  return call(
    'put',
    '/transfer/'+str(transfer['id']),
    { 'key': transfer['files'][0]['uid'] },
    { 'complete': True },
    None,
    {}
  )

def deleteTransfer(transfer):
  return call(
    'delete',
    '/transfer/'+str(transfer['id']),
    { 'key': transfer['files'][0]['uid'] },
    None,
    None,
    {}
  )

##########################################################################

#postTransfer
if debug:
  print('postTransfer')

files = {}
filesTransfer = []
for f in args.files:
  fn_abs = os.path.abspath(f)
  fn = os.path.basename(fn_abs)
  size = os.path.getsize(fn_abs)

  files[fn+':'+str(size)] = {
    'name':fn,
    'size':size,
    'path':fn_abs
  }
  filesTransfer.append({'name':fn,'size':size})

troptions = {'get_a_link':0}


transfer = postTransfer( username,
                         filesTransfer,
                         args.recipients,
                         subject=args.subject,
                         message=args.message,
                         expires=None,
                         options=troptions)['created']
#print(transfer)

try:
  for f in transfer['files']:
    path = files[f['name']+':'+str(f['size'])]['path']
    size = files[f['name']+':'+str(f['size'])]['size']
    #putChunks
    if debug:
      print('putChunks: '+path)
    with open(path, mode='rb', buffering=0) as fin:
      for offset in range(0,size+1,upload_chunk_size):
        if progress:
          print('Uploading: '+path+' '+str(offset)+'-'+str(min(offset+upload_chunk_size, size))+' '+str(round(offset/size*100))+'%')
        data = fin.read(upload_chunk_size)
        #print(data)
        putChunk(transfer, f, data, offset)

    #fileComplete
    if debug:
      print('fileComplete: '+path)
    fileComplete(transfer,f)
    if progress:
      print('Uploading: '+path+' '+str(size)+' 100%')


  #transferComplete
  if debug:
    print('transferComplete')
  transferComplete(transfer)
  if progress:
    print('Upload Complete')

except Exception as inst:
  print(type(inst))
  print(inst.args)
  print(inst)

  #deleteTransfer
  if debug:
    print('deleteTransfer')
  deleteTransfer(transfer)
  `

**Comment by KenRoy-Octo** [comment] 2023-01-29 03:09
This version of filesender.py is reformatted and uses the "from_address" instead of "userid" so I think it may make more sense. 

```
#!/usr/bin/env python3
#
# FileSender www.filesender.org
#
# Copyright (c) 2009-2019, AARNet, Belnet, HEAnet, SURFnet, UNINETT
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# *   Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
# *   Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
# *   Neither the name of AARNet, Belnet, HEAnet, SURFnet and UNINETT nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import argparse

try:
    import requests
    import time
    from collections.abc import Iterable
    from collections.abc import MutableMapping
    import hmac
    import hashlib
    import urllib3
    import os
    import json
    import configparser
    from os.path import expanduser
except Exception as e:
    print(type(e))
    print(e.args)
    print(e)
    print('')
    print('ERROR: A required dependency is not installed, please check your')
    print('distribution packages or run something like the following')
    print('')
    print('pip3 install requests urllib3 ')
    exit(1)

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Globals
_PARSER = None


################################
# If error, print usage and exit
################################
def print_usage_and_exit(err_message):
    global _PARSER
    print("\n" + err_message + "\n")
    _PARSER.print_help()
    exit(1)


#####################################
# Read data from 'ini' and set values
#####################################
def get_config_data():
    # default settings
    base_url = 'DEFAULT BASE URL'
    default_transfer_days_valid = 10
    username = None
    apikey = None

    try:
        config = configparser.ConfigParser()
        config.read(expanduser("~") + '/.filesender/filesender.py.ini')
        if 'system' in config:
            base_url = config['system'].get('base_url', base_url)
            default_transfer_days_valid = int(config['system'].get('default_transfer_days_valid',
                                                                   default_transfer_days_valid))
        if 'user' in config:
            username = config['user'].get('username')
            apikey = config['user'].get('apikey')
        # if we have found these in the config file they become optional arguments
        if username is None or apikey is None:
            print_usage_and_exit('Missing username or apikey in ini file!')

    except Exception as err:
        print_usage_and_exit('Error in ini file: error = {e}'.format(e=str(err)))

    return [base_url, default_transfer_days_valid, username, apikey]


######################################
# Set and check command-line arguments
######################################
def process_options():
    global _PARSER
    epilog_str = '''This script requires a configuration file called ".filesender/filesender.py.ini" in the user's \
    home directory: \n\
    Example: \n\
    [system] \n\
    base_url=https://files.di2e.net/filesender2/rest.php \n\
    default_transfer_days_valid=10 \n\
    [user] \n\
    username=username \n\
    apikey=c69d4c... '''

    _PARSER = argparse.ArgumentParser(epilog=epilog_str, formatter_class=argparse.RawTextHelpFormatter)
    _PARSER.add_argument("--hostname", help="destination host")
    _PARSER.add_argument("files", help="path to file(s) to send", nargs='+')
    _PARSER.add_argument("-v", "--verbose", action="store_true", help="verbose output")
    _PARSER.add_argument("-i", "--insecure", action="store_true", help="insecure flag to bypass ssl error warning")
    _PARSER.add_argument("-p", "--progress", action="store_true", help="progress flag")
    _PARSER.add_argument("-s", "--subject", help="filesender email subject")
    _PARSER.add_argument("-f", "--from_address", help="filesender email from address")
    _PARSER.add_argument("-m", "--message", help="filesender email message")
    required_named = _PARSER.add_argument_group('required named arguments')
    required_named.add_argument("-r", "--recipients", required=True)

    args = _PARSER.parse_args()
    return args


##############################
# Reorganize data for API CALL
##############################
def flatten(d, parent_key=''):
    items = []
    for k, v in d.items():
        new_key = parent_key + '[' + k + ']' if parent_key else k
        if isinstance(v, MutableMapping):
            items.extend(flatten(v, new_key).items())
        else:
            items.append(new_key + '=' + v)
    items.sort()
    return items


######################################
# Execute network requests (API CALLS)
######################################
def call(site_info, method, path, data, content=None, raw_content=None, options={}):
    signed = bytes(method + '&' +
                   site_info['base_url'].replace('https://', '', 1).replace('http://', '', 1) + path +
                   '?' + ('&'.join(flatten(data))), 'ascii')

    content_type = options['Content-Type'] if 'Content-Type' in options else 'application/json'

    input_content = None
    if content is not None and content_type == 'application/json':
        input_content = json.dumps(content, separators=(',', ':'))
        signed += bytes('&' + input_content, 'ascii')
    elif raw_content is not None:
        input_content = raw_content
        signed += bytes('&', 'ascii')
        signed += input_content

    # print(signed)
    bkey = bytearray()
    bkey.extend(map(ord, site_info['apikey']))
    data['signature'] = hmac.new(bkey, signed, hashlib.sha1).hexdigest()

    url = site_info['base_url'] + path + '?' + ('&'.join(flatten(data)))
    headers = {
        "Accept": "application/json",
        "Content-Type": content_type
    }
    response = None
    if method == "get":
        response = requests.get(url, verify=not site_info['insecure'], headers=headers)
    elif method == "post":
        response = requests.post(url, data=input_content, verify=not site_info['insecure'], headers=headers)
    elif method == "put":
        response = requests.put(url, data=input_content, verify=not site_info['insecure'], headers=headers)
    elif method == "delete":
        response = requests.delete(url, verify=not site_info['insecure'], headers=headers)

    if response is None:
        raise Exception('Client error')

    code = response.status_code
    # print(url)
    # print(inputcontent)
    # print(code)
    # print(response.text)

    if code != 200:
        if method != 'post' or code != 201:
            raise Exception('Http error ' + str(code) + ' ' + response.text)

    if response.text == "":
        raise Exception('Http error ' + str(code) + ' Empty response')

    if method != 'post':
        return response.json()

    r = {'location': response.headers['Location'], 'created': response.json()}
    return r


########################
# API POST transfer call
########################
def post_transfer(site_info, files, expires=None, options=[]):
    if expires is None:
        expires = round(time.time()) + (site_info['default_transfer_days_valid'] * 24 * 3600)

    to = [x.strip() for x in site_info['recipients'].split(',')]

    return call(
        site_info,
        'post',
        '/transfer',
        {'remote_user': site_info['username'], 'timestamp': str(round(time.time()))},
        {
            'from': site_info['from_address'],
            'files': files,
            'recipients': to,
            'subject': site_info['subject'],
            'message': site_info['message'],
            'expires': expires,
            'aup_checked': 1,
            'options': options
        },
        None,
        {}
    )


####################################
# API PUT 'file chunk' transfer call
####################################
def put_chunk(site_info, t, f, chunk, offset):
    return call(
        site_info,
        'put',
        '/file/' + str(f['id']) + '/chunk/' + str(offset),
        {'key': f['uid'], 'roundtriptoken': t['roundtriptoken'],
         'remote_user': site_info['username'], 'timestamp': str(round(time.time()))},
        None,
        chunk,
        {'Content-Type': 'application/octet-stream'}
    )


#######################################
# API PUT 'file complete' transfer call
#######################################
def file_complete(site_info, t, f):
    return call(
        site_info,
        'put',
        '/file/' + str(f['id']),
        {'key': f['uid'], 'roundtriptoken': t['roundtriptoken'],
         'remote_user': site_info['username'], 'timestamp': str(round(time.time()))},
        {'complete': True},
        None,
        {}
    )


##################################
# API PUT 'transfer complete' call
##################################
def transfer_complete(site_info, transfer):
    return call(
        site_info,
        'put',
        '/transfer/' + str(transfer['id']),
        {'key': transfer['files'][0]['uid'],
         'remote_user': site_info['username'], 'timestamp': str(round(time.time()))},
        {'complete': True},
        None,
        {}
    )


############################
# API DELETE 'transfer' call
############################
def delete_transfer(site_info, transfer):
    return call(
        site_info,
        'delete',
        '/transfer/' + str(transfer['id']),
        {'key': transfer['files'][0]['uid'],
         'remote_user': site_info['username'], 'timestamp': str(round(time.time()))},
        None,
        None,
        {}
    )


#############################
# Query API to get chunk size
#############################
def get_upload_chunk_size(base_url, insecure):
    # configs
    try:
        response = requests.get(base_url + '/info', verify=True)
    except requests.exceptions.SSLError as exc:
        if not insecure:
            print('Error: the SSL certificate of the server you are connecting to cannot be verified:')
            print(exc)
            print('For more information, please refer to https://www.digicert.com/ssl/. \
                If you are absolutely certain of the identity of the server you are connecting to, you can use the \
                --insecure flag to bypass this warning. Exiting...')
            exit(1)
        elif insecure:
            print('Warning: Error: the SSL certificate of the server you are connecting to cannot be verified:')
            print(exc)
            print('Running with --insecure flag, ignoring warning...')
            response = requests.get(base_url + '/info', verify=False)
    if response.status_code is not 200:
        print("Error from server: status_code = {s}.".format(s=response.status_code))
        exit(1)
    upload_chunk_size = response.json()['upload_chunk_size']
    return upload_chunk_size


################
# Upload file(s)
################
def execute_upload(args, site_info):
    files = {}
    files_transfer = []
    for f in args.files:
        fn_abs = os.path.abspath(f)
        fn = os.path.basename(fn_abs)
        size = os.path.getsize(fn_abs)

        files[fn + ':' + str(size)] = {
            'name': fn,
            'size': size,
            'path': fn_abs
        }
        files_transfer.append({'name': fn, 'size': size})

    troptions = {'get_a_link': 0}

    transfer = post_transfer(site_info,
                             files_transfer,
                             expires=None,
                             options=troptions)['created']
    try:
        for f in transfer['files']:
            path = files[f['name'] + ':' + str(f['size'])]['path']
            size = files[f['name'] + ':' + str(f['size'])]['size']
            # putChunks
            if args.verbose:
                print('putChunks: ' + path)
            with open(path, mode='rb', buffering=0) as fin:
                for offset in range(0, size + 1, site_info['upload_chunk_size']):
                    if args.progress:
                        print('Uploading: ' + path + ' ' + str(offset) + '-' + str(
                            min(offset + site_info['upload_chunk_size'], size)) + ' ' +
                              str(round(offset / size * 100)) + '%')
                    data = fin.read(site_info['upload_chunk_size'])
                    # print(data)
                    put_chunk(site_info, transfer, f, data, offset)

            # fileComplete
            if args.verbose:
                print('fileComplete: ' + path)
            file_complete(site_info, transfer, f)
            if args.progress:
                print('Uploading: ' + path + ' ' + str(size) + ' 100%')

        # transferComplete
        if args.verbose:
            print('transferComplete')
        transfer_complete(site_info, transfer)
        if args.progress:
            print('Upload Complete')

    except Exception as inst:
        print(type(inst))
        print(inst.args)
        print(inst)

        # deleteTransfer
        if args.verbose:
            print('deleteTransfer')
        delete_transfer(site_info, transfer)


######
# MAIN
######
def main():
    args = process_options()
    [base_url, default_transfer_days_valid, username, apikey] = get_config_data()
    from_address = username
    if hasattr(args, 'from_address'):
        from_address = args.from_address

    debug = args.verbose
    insecure = args.insecure

    upload_chunk_size = get_upload_chunk_size(base_url, insecure)

    site_info = {'base_url': base_url,
                 'default_transfer_days_valid': default_transfer_days_valid,
                 'username': username,
                 'apikey': apikey,
                 'from_address': from_address,
                 'insecure': insecure,
                 'recipients': args.recipients,
                 'subject': args.subject,
                 'message': args.message,
                 'upload_chunk_size': upload_chunk_size}

    if debug:
        print('base_url          : ' + base_url)
        print('username          : ' + username)
        print('apikey            : ' + apikey)
        print('upload_chunk_size : ' + str(upload_chunk_size) + ' bytes')
        print('recipients        : ' + args.recipients)
        print('files             : ' + ','.join(args.files))
        print('insecure          : ' + str(insecure))
        print('from_address      : ' + from_address)

    # postTransfer
    if debug:
        print('postTransfer')

    execute_upload(args, site_info)

    if debug:
        print("DONE!")


############
# START HERE
############
if __name__ == '__main__':
    main()
```

**Comment by KenRoy-Octo** [comment] 2023-01-29 15:00
Since my filesender.py is a complete overhaul of the original, then it would need to completely replace the original if this script is acceptable.  It is backwards compatible so it should not impact the way others are using it (I hope ;-) ).

**Comment by KenRoy-Octo** [comment] 2023-03-28 11:03
I don't have permission to create a branch

**Comment by WebSpider** [comment] 2023-03-28 11:24
On github, you normally create a fork of the project (https://github.com/filesender/filesender/fork) in which you do your changes, preferrably in a new branch, since you can create a new branch in your own fork/copy of the project.

Then you create a Pull Request (https://github.com/filesender/filesender/compare) where you ask for the changes to be merged into the mainstream filesender.

Hope that helps!

**Comment by peter-** [comment] 2023-06-30 15:38
> But I do have an issue with the filesender.py script. It makes an assumption that the username is an email and so uses it both for "remote_user" and "mail from" fields.

FWIW, our user names are not email addresses (though they are qualified with a domain for global uniqueness) and I have had no issues with our use of Filesender or its Python API client. Could you be more specific about the issue you're experiencing when using the original client *as is*, such as errors, warnings, mis-features?

> We are currently just rewriting filesender.py to accommodate this, but prefer to not have to maintain this change for every new version of filesender.

Unfortunately your later included rewrite (affecting lots of unrelated areas, essentially everything appears changed) does not particularly invite a review of the *specific changes you desire in the context of this issue*.

Bundling related changes for specific aspects into separate issues/pull requests is how you enable others to review and ultimately incorporate your changes, by keeping each change set traceable and comprehensible in isolation.  The chosen approach of "here's my complete rewrite of your code, you can search through all of the code in order to determine what I may have changed or not and where I merely may have rearranged or reformatted lines/blocks of code" makes that review process needlessly complex.

Hopefully that helps in understanding why and how best to cooperate in this context.

**Comment by WebSpider** [comment] 2023-09-26 08:35
The essential parts of this rewrite have been merged into `development` with #1442 and are scheduled to be in the next release

**Comment by WebSpider** [comment] 2023-11-30 14:13
This has been released with version 2.42

**Closed by WebSpider** 2023-11-30 14:13 UTC
Labels: feedback-needed, fix merged
