### ISSUE TITLE
tar archive don't have the correct filename like with zip

### ISSUE THREAD

**Issue by belnet-ming** [filesender/filesender#594] opened 2019-07-16 08:43 UTC
Tar archive don't have the correct filename like with zip archive.
Downloaded tar archive filename defaulted to "download.php".

**Comment by monkeyiq** [comment] 2019-08-01 08:24
which browser are you using for the test. Is ok with latest firefox here. I get something like transfer_377_files_somehex.tar as the archive name. 

This is tested post merge of https://github.com/filesender/filesender/pull/595

**Comment by monkeyiq** [comment] 2019-08-01 08:26
I think I see why 595 might be updating things. I'll have to investigate and test a bit more.

**Comment by monkeyiq** [comment] 2019-08-08 10:47
I merged https://github.com/filesender/filesender/pull/605 to clean things up a little. I am getting the tar archive name ok here in Firefox and Chrome. Please feel free to reopen if you are still seeing this on any setup.

**Comment by fransward** [comment] 2019-08-14 13:31
Unfortunately the same results as before: a zip file will be downloaded if I choose the 'Download as single (.tar) file.'.
Tested with a Chrome and Firefox browser and Mac OS.

**Comment by monkeyiq** [comment] 2019-08-15 00:28
Hmm, trying to get this issue here on osx using firefox and chrome and downloading the tar I get a tar file with the expected name. It might be a deeper thing than browser version etc, hopefully I can work out how to trigger it here.

```
osx:Downloads ben$ file transfer_548_files_84037cc9.tar
transfer_548_files_84037cc9.tar: POSIX tar archive
osx:Downloads ben$ tar tvf transfer_548_files_84037cc9.tar
-rwxrwxrwx  0 0      0          32 Aug 15 10:21 df-3.txt
-rwxrwxrwx  0 0      0          32 Aug 15 10:21 df-2.txt
```

From your above you are saying that you get a zip file if you choose either download as tar or download as zip?

**Comment by monkeyiq** [comment] 2019-08-15 00:34
I created 613 above to log the archive type and filename to try to work out what is happening to lead to the wrong archive type.

**Comment by monkeyiq** [comment] 2019-08-15 04:55
https://github.com/filesender/filesender/pull/616 logs the format it wants to download in the browser console too. 613 is no longer in use, 616 is the current test.

**Comment by fransward** [comment] 2019-08-15 21:27
Yes, in both archive download options I get the ZIP file. With the #616 in place I saw a suspicious URL in the browser console:

`GET https://filesenderbeta.surf.nl/download.php?token=xxxx-xxxx-xxxx-xxxx&files_ids=286%2C287`

Following the code I suspected a:

`GET https://filesenderbeta.surf.nl/download.php?token=xxxxxx-xxxxxx-xxxxxx-xxxxx&archive_format=tar&files_ids=286,287&notify_upon_completion=1`

Notice the missing **&archive_format=tar** in the first GET.

I suspected this strange behaviour is caused by one of the settings in config.php. We have had problems before when suddenly popups (i.e. telling you an upload was finished) didn't appear anymore.

So I start commenting lines out until I noticed that the culprit lies herein:
```
// Recipient is asked whether he wants to get an email stating that the download is complete
    'enable_recipient_email_download_complete' => array(
        'available' => false,
        'advanced' => false,
        'default' => false
    ),
```

Only when you use **'default' => true** the correct .tar extension will be produced.

**Comment by fransward** [comment] 2019-08-15 21:31
Btw, this is in the User Transfers section of the config.

`$config['transfer_options']`

PS: The remark about missing popups is about these lines of config settings:

```
// DO NOT ENABLE - WILL DESTROY POPUPS
//    'redirect_url_on_complete' => array(
//        'available' => false,
//        'advanced' => false,
//        'default' => 'https://filesenderbeta.surf.nl/',
//        'complex' => true,
//    ),
```

**Comment by monkeyiq** [comment] 2019-08-15 23:28
This is great information! The issue should be fixed with https://github.com/filesender/filesender/pull/617.

**Comment by fransward** [comment] 2019-08-16 06:45
Confirmed! Now when I use   'default' => true  the .tar extension is used when I download as .tar.

```
    'enable_recipient_email_download_complete' => array(
        'available' => false,
        'advanced' => false,
        'default' => true
    ),
```

**Closed** 2019-08-16 22:53 UTC
